project_id = "dvbklbeevpaicwavobox"

[functions.sync-matches]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.oidc-callback]
verify_jwt = false

[functions.oidc-token-auth]
verify_jwt = false

[functions.cleanup-unconsented-users]
verify_jwt = false

[functions.generate-boost-image]
verify_jwt = false

[functions.translate-boost]
verify_jwt = false