project_id = "dvbklbeevpaicwavobox"

[functions.sync-matches]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.oidc-callback]
verify_jwt = false
